name: Linter

on:
  push:
    branches:
    - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.8.3
        with:
          pixi-version: v0.39.5
          environments: lint
          frozen: false

      - name: Run linter
        run: pixi run -e lint lint
